server:
  port: 8080
  servlet:
    context-path: /email-service
spring:
  application:
    name: email-service
  mvc:
    static-path-pattern: /rs/**
  profiles:
    active: dev
quantex:
  application:
    name: email-service
    jwt-secret: quantex
  mybatis:
    mapper-locations:
#    - classpath:com/iquantex/web/framework/dao/basexml/*.xml
#    - classpath:com/iquantex/web/framework/dao/xml/*.xml
#    - classpath:com/iquantex/msgcenter/dao/basexml/*.xml
    type-aliases-packages:
#    - com.iquantex.web.framework.model
#    - com.iquantex.msgcenter.model
    base-packages:
#    - com.iquantex.web.framework.dao.java
#    - com.iquantex.msgcenter.dao.java
    properties:
      ORDER: BEFORE
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
logging:
  file: logs/email-service.log
  level:
    com.iquantex: debug
    root: info
mybatis-plus:
  configuration:
    # 开启MyBatis的SQL打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
